steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [
            'build',
            '-t',
            'australia-southeast1-docker.pkg.dev/python-362007/test-repo/test-image:${SHORT_SHA}',
            '-t',
            'australia-southeast1-docker.pkg.dev/python-362007/test-repo/test-image:latest',
            '--cache-from',
            'australia-southeast1-docker.pkg.dev/python-362007/test-repo/test-image:latest',
            '--file',
            'gcp-artifact-registry/Dockerfile',
            '.'
          ]

  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'australia-southeast1-docker.pkg.dev/python-362007/test-repo/test-image:${SHORT_SHA}']

# Store images in Google Artifact Registry 
images:
  - australia-southeast1-docker.pkg.dev/python-362007/test-repo/test-image:${SHORT_SHA}
  - australia-southeast1-docker.pkg.dev/python-362007/test-repo/test-image:latest
